"""
The Action Catalog — the single, authoritative list of every action a user can
perform in the Logistics Control Tower, module by module, sub-module by
sub-module, tab by tab.

This file answers three questions in one place:

  1. WHAT can a human do here?      → the catalog rows
  2. CAN ATLAS do it autonomously?  → `ai_capable` + `autonomy`
  3. WHEN must a human decide?      → `autonomy: human`/`dual` + `approval_trigger`
                                      + the severity / confidence / value gates

Everything downstream reads from here:

  * `ACTION_THRESHOLDS`  — the per-action autonomy policy the agent engine
    evaluates before it self-executes anything (derived, not hand-maintained).
  * The Governance tab   — renders the catalog verbatim, so what the operator
    reads is literally the policy the engine enforces.
  * The reasoning tracer — uses `consults` to decide which specialist
    capabilities are pulled into the cross-agent negotiation for an action.

AUTONOMY CLASSES
    observe   Read, filter, drill, navigate. ATLAS does these continuously and
              silently — there is nothing to approve.
    auto      State-changing, but routine, bounded and reversible. Self-executes
              while severity ≤ ceiling, confidence ≥ floor and value ≤ ceiling.
              Any breach of a gate escalates it to a human.
    human     Always escalated. High stakes, irreversible, contractual,
              reputational or regulatory — judgement the business owns.
    dual      Escalated AND requires a second approver above the dual-control
              value line.

REVERSIBILITY / BLAST RADIUS are the two levers that decide which class an
action lands in: an action that is irreversible OR network-wide is never `auto`.
"""

from __future__ import annotations

# ── Modules · the navigation spine ───────────────────────────────────────────
MODULES = {
    "/":               {"label": "Executive Dashboard",    "icon": "LayoutDashboard", "accent": "#8B5CF6", "section": "Overview"},
    "/visibility":     {"label": "Live Visibility Hub",    "icon": "Radar",           "accent": "#6366F1", "section": "Operations"},
    "/transport":      {"label": "Transport Control",      "icon": "Truck",           "accent": "#F59E0B", "section": "Operations"},
    "/demand":         {"label": "Demand & Inventory",     "icon": "Package",         "accent": "#3B82F6", "section": "Operations"},
    "/iot":            {"label": "IoT & Smart Tech",       "icon": "Cpu",             "accent": "#10B981", "section": "Operations"},
    "/sustainability": {"label": "Sustainability",         "icon": "Leaf",            "accent": "#22C55E", "section": "Operations"},
    "/exceptions":     {"label": "Exceptions",             "icon": "AlertTriangle",   "accent": "#EF4444", "section": "Risk Management"},
    "/simulator":      {"label": "Scenario Simulator",     "icon": "Clapperboard",    "accent": "#EC4899", "section": "Risk Management"},
    "/risk":           {"label": "Supplier & Labour Risk", "icon": "ShieldCheck",     "accent": "#0EA5E9", "section": "Risk Management"},
    "/ai":             {"label": "AI Command Center",      "icon": "Sparkles",        "accent": "#8B5CF6", "section": "Agentic Layer"},
    "/platform":       {"label": "Platform & Session",     "icon": "Settings",        "accent": "#64748B", "section": "Platform"},
}

AUTONOMY_CLASSES = {
    "observe": {"label": "Observe", "blurb": "Read-only. ATLAS does this continuously — nothing to approve.", "color": "#64748B"},
    "auto":    {"label": "Autonomous", "blurb": "Self-executes inside its guardrails; breaches escalate to a human.", "color": "#10B981"},
    "human":   {"label": "Human decision", "blurb": "Always escalated for approval — ATLAS prepares, a human decides.", "color": "#8B5CF6"},
    "dual":    {"label": "Dual control", "blurb": "Escalated, and a second approver is required above the dual-control line.", "color": "#EF4444"},
}

CATEGORIES = {
    "observe": {"label": "Observe & navigate", "order": 1},
    "analyse": {"label": "Analyse & model",    "order": 2},
    "execute": {"label": "Execute & change",  "order": 3},
    "govern":  {"label": "Govern & configure", "order": 4},
}

_RISK = ("record", "site", "region", "network")


def _a(key, label, *, module, tab, section, category, permission=None, agent=None,
       autonomy="observe", threshold_key=None, severity_ceiling="medium",
       confidence_floor=70, value_ceiling_gbp=0, commits_spend=False,
       reversibility="reversible", blast_radius="record", sla_minutes=None,
       approval_trigger=None, why_human=None, consults=(), executes=None, description=""):
    """One catalog row. Defaults describe a harmless read; every state change
    overrides them explicitly so nothing becomes autonomous by accident.

    `commits_spend` decides whether the GLOBAL auto-approve guardrail bites. It
    is set only where money actually leaves the business — a purchase order, an
    expedite premium. Relocating stock the business already owns has a value, but
    it is not spend, so it is governed by its own ceiling alone. Conflating the
    two would either cap transfers absurdly low or let purchasing run too free.
    """
    return {
        "key": key, "label": label, "description": description,
        "module": module, "module_label": MODULES[module]["label"],
        "tab": tab, "section": section, "category": category,
        "permission": permission, "agent": agent,
        "ai_capable": autonomy != "none",
        "autonomy": autonomy, "threshold_key": threshold_key,
        "severity_ceiling": severity_ceiling, "confidence_floor": confidence_floor,
        "value_ceiling_gbp": value_ceiling_gbp, "commits_spend": commits_spend,
        "reversibility": reversibility, "blast_radius": blast_radius,
        "sla_minutes": sla_minutes,
        "approval_trigger": approval_trigger or (
            "Never — read-only" if autonomy == "observe" else "Always"),
        "why_human": why_human, "consults": list(consults),
        "executes": executes or label,
    }


# ═════════════════════════════════════════════════════════════════════════════
# THE CATALOG
# ═════════════════════════════════════════════════════════════════════════════

ACTION_CATALOG: list[dict] = [

    # ── 1 · EXECUTIVE DASHBOARD ──────────────────────────────────────────────
    _a("dash.view_kpis", "Review executive KPI grid", module="/", tab="Executive KPIs",
       section="KPI Grid", category="observe", permission="read:analytics", agent="orchestrator",
       description="Read the nine board-level KPIs with RAG status, target and trend."),
    _a("dash.kpi_definition", "Open a KPI definition", module="/", tab="Executive KPIs",
       section="KPI Grid", category="observe", permission="read:analytics", agent="orchestrator",
       description="Inspect how a KPI is calculated, its target and its data source."),
    _a("dash.view_ai_insights", "Read the AI insight panel", module="/", tab="AI Insights",
       section="Daily Briefing", category="observe", permission="read:analytics", agent="orchestrator",
       description="The active scenario's risk plan and ATLAS's ranked view of the network."),
    _a("dash.drill_module", "Drill from a KPI into its module", module="/", tab="Executive KPIs",
       section="KPI Grid", category="observe", permission="read:analytics", agent="orchestrator"),
    _a("dash.exception_summary", "Review the open-exception summary", module="/", tab="Exceptions Summary",
       section="Exception Rollup", category="observe", permission="read:analytics", agent="exception"),
    _a("dash.publish_briefing", "Publish the daily control-tower briefing", module="/", tab="AI Insights",
       section="Daily Briefing", category="execute", permission="read:analytics", agent="orchestrator",
       autonomy="auto", threshold_key="publish_briefing", severity_ceiling="low",
       confidence_floor=60, reversibility="reversible", blast_radius="network",
       consults=("replenishment", "exception", "supplier", "transport"),
       approval_trigger="Never — it is a summary, it changes no operational state",
       executes="Compiles and posts the ranked daily briefing to every operator's dashboard.",
       description="Summarise the network's state, rank the day's risks and post the briefing."),

    # ── 2 · LIVE VISIBILITY HUB ──────────────────────────────────────────────
    _a("vis.map_layers", "Toggle live map layers", module="/visibility", tab="Overview",
       section="Live Map", category="observe", permission="read:field", agent="visibility",
       description="Show/hide engineers, lockers, shipments and warehouses on the map."),
    _a("vis.select_engineer", "Open an engineer's live position", module="/visibility", tab="Engineers",
       section="Engineer Tracking", category="observe", permission="read:field", agent="visibility"),
    _a("vis.filter_engineers", "Filter engineers by status or business unit", module="/visibility", tab="Engineers",
       section="Engineer Tracking", category="observe", permission="read:field", agent="visibility"),
    _a("vis.view_lockers", "Review the ByBox locker network", module="/visibility", tab="Lockers",
       section="Locker Network", category="observe", permission="read:field", agent="visibility"),
    _a("vis.view_hubs", "Review warehouse throughput", module="/visibility", tab="Hubs",
       section="Warehouse Throughput", category="observe", permission="read:field", agent="visibility"),
    _a("vis.view_inbound", "Track inbound shipments and ETA deviation", module="/visibility", tab="Overview",
       section="Inbound Shipments", category="observe", permission="read:field", agent="visibility"),
    _a("vis.locker_failover", "Fail over offline lockers to healthy sites", module="/visibility", tab="Lockers",
       section="Locker Network", category="execute", permission="read:field", agent="visibility",
       autonomy="auto", threshold_key="locker_failover", severity_ceiling="high",
       confidence_floor=70, reversibility="reversible", blast_radius="region", sla_minutes=45,
       consults=("transport", "orchestrator"),
       approval_trigger="Confidence < 70%, severity critical, or more than 25 sites in one sweep",
       executes="Re-points affected lockers to their nearest healthy site and notifies the engineers.",
       description="Move engineer collections off dead lockers before the pre-8AM window fails."),
    _a("vis.reroute_inbound", "Reroute cover stock for a delayed inbound", module="/visibility", tab="Overview",
       section="Inbound Shipments", category="execute", permission="read:field", agent="visibility",
       autonomy="auto", threshold_key="reroute_inbound", severity_ceiling="high",
       confidence_floor=70, reversibility="reversible", blast_radius="region", sla_minutes=60,
       consults=("replenishment", "transport"),
       approval_trigger="Confidence < 70% or the delay is critical to a P1 exception",
       executes="Pulls cover stock from the nearest hub for jobs booked against the delayed load."),
    _a("vis.unlock_locker", "Unlock a locker for an engineer", module="/visibility", tab="Lockers",
       section="Locker Network", category="execute", permission="read:field", agent="visibility",
       autonomy="auto", threshold_key="locker_unlock", severity_ceiling="medium",
       confidence_floor=75, reversibility="reversible", blast_radius="record", sla_minutes=15,
       consults=("transport",),
       approval_trigger="Engineer identity unverified, or the site is outside their round",
       executes="Issues a one-time unlock code for the named engineer at the named site."),
    _a("vis.flag_throughput", "Flag a warehouse throughput collapse", module="/visibility", tab="Hubs",
       section="Warehouse Throughput", category="execute", permission="read:field", agent="visibility",
       autonomy="auto", threshold_key="flag_throughput", severity_ceiling="high",
       confidence_floor=72, reversibility="reversible", blast_radius="site", sla_minutes=30,
       consults=("exception", "orchestrator"),
       approval_trigger="Raising it as a P1 — a P1 declaration is always a human call",
       executes="Raises a throughput exception against the site and notifies the 3PL duty manager."),

    # 2a · Van stock alerts — four genuinely different answers to one shortage.
    # Moving stock we already hold is bounded and reversible; changing a named
    # person's day is not, which is why they sit in different autonomy classes.
    _a("vis.view_van_alerts", "Work the van stock alert queue", module="/visibility", tab="Van Alerts",
       section="Van Stock Alerts", category="observe", permission="read:field", agent="visibility",
       description="Every van below minimum, ranked by the jobs it puts at risk, with its options priced."),
    _a("vis.van_inter_transfer", "Move stock van-to-van", module="/visibility", tab="Van Alerts",
       section="Van Stock Alerts", category="execute", permission="write:transfer", agent="visibility",
       autonomy="auto", threshold_key="van_inter_transfer", severity_ceiling="high",
       confidence_floor=70, value_ceiling_gbp=2500, reversibility="reversible", blast_radius="record",
       sla_minutes=60, consults=("transport", "replenishment"),
       approval_trigger="Donor van more than 25 miles away, or the move would drop the donor below its own minimum",
       executes="Books the hand-over between the two engineers at a midpoint and moves the stock on both vans.",
       description="Cover a shortage from surplus already in the field — no new spend, no new delivery."),
    _a("vis.van_job_reallocation", "Reallocate a job off a short van", module="/visibility", tab="Van Alerts",
       section="Van Stock Alerts", category="execute", permission="write:transfer", agent="visibility",
       autonomy="human", threshold_key="van_job_reallocation", severity_ceiling="high",
       confidence_floor=80, reversibility="compensable", blast_radius="region", sla_minutes=45,
       consults=("transport", "orchestrator"),
       why_human="Reallocation rewrites two named people's working day and can breach drivers' hours. "
                 "It needs a dispatcher who knows the crew.",
       approval_trigger="Always — it changes two individuals' shifts",
       executes="Moves the appointment onto the covering engineer's route and notifies both parties."),
    _a("vis.van_collect_en_route", "Add a parts-collection stop en route", module="/visibility", tab="Van Alerts",
       section="Van Stock Alerts", category="execute", permission="write:locker", agent="visibility",
       autonomy="auto", threshold_key="van_collect_en_route", severity_ceiling="high",
       confidence_floor=70, reversibility="reversible", blast_radius="record", sla_minutes=30,
       consults=("transport", "replenishment"),
       approval_trigger="Detour over 45 minutes, or the insertion pushes an SLA appointment past its window",
       executes="Inserts a collection stop at the nearest locker or hub into the van's route in Transport Control.",
       description="Send the van via a forward stock location before the job that needs the part."),
    _a("vis.van_replenishment_order", "Raise a van replenishment order", module="/visibility", tab="Van Alerts",
       section="Van Stock Alerts", category="execute", permission="write:po", agent="replenishment",
       autonomy="auto", threshold_key="van_replenishment_order", severity_ceiling="high",
       confidence_floor=70, value_ceiling_gbp=5000, commits_spend=True, reversibility="compensable",
       blast_radius="record", sla_minutes=720, consults=("transport", "replenishment"),
       approval_trigger="Order value over £5k, or a same-day premium slot rather than the standard overnight wave",
       executes="Posts the order to Field Service and books the overnight leg to the engineer's home locker.",
       description="Restore the van to standard quantities on tonight's wave — the structural fix, not today's."),

    # 2b · Pre-8AM locker misses.
    _a("vis.view_locker_misses", "Work the pre-8AM miss queue", module="/visibility", tab="Lockers",
       section="Pre-8AM Misses", category="observe", permission="read:field", agent="visibility",
       description="Sites that missed the overnight wave, why they missed it, and who it strands."),
    _a("vis.locker_master_key", "Issue a master-key override", module="/visibility", tab="Lockers",
       section="Pre-8AM Misses", category="execute", permission="write:locker", agent="visibility",
       autonomy="human", threshold_key="locker_master_key", severity_ceiling="high",
       confidence_floor=75, reversibility="compensable", blast_radius="site", sla_minutes=20,
       consults=("transport", "replenishment"),
       why_human="An override lets engineers take stock nobody has confirmed is there. It trades "
                 "inventory accuracy for a working morning — a judgement about which matters more today.",
       approval_trigger="Always — it suspends stock control at the site",
       executes="Issues a time-boxed master-key code and flags the site for reconciliation."),
    _a("vis.locker_second_wave", "Book a same-day catch-up drop", module="/visibility", tab="Lockers",
       section="Pre-8AM Misses", category="execute", permission="write:locker", agent="visibility",
       autonomy="human", threshold_key="locker_second_wave", severity_ceiling="high",
       confidence_floor=75, value_ceiling_gbp=1500, commits_spend=True, reversibility="compensable",
       blast_radius="site", sla_minutes=60, consults=("transport", "replenishment", "sustainability"),
       why_human="A dedicated same-day run is premium freight bought outside the plan. Whether the "
                 "morning is worth it is a commercial call.",
       approval_trigger="Always — it commits unplanned freight spend",
       executes="Books a same-day dedicated leg from the hub and tracks it in Transport Control."),
    _a("vis.locker_hub_collection", "Divert collections to a hub counter", module="/visibility", tab="Lockers",
       section="Pre-8AM Misses", category="execute", permission="write:locker", agent="visibility",
       autonomy="auto", threshold_key="locker_hub_collection", severity_ceiling="high",
       confidence_floor=70, reversibility="reversible", blast_radius="region", sla_minutes=45,
       consults=("transport",),
       approval_trigger="Hub more than 40 miles away, or the detour breaches an engineer's first SLA appointment",
       executes="Re-points affected engineers to the hub trade counter and notifies them before they travel."),
    _a("vis.locker_in_boot_switch", "Switch a site to in-boot delivery", module="/visibility", tab="Lockers",
       section="Pre-8AM Misses", category="execute", permission="write:locker", agent="visibility",
       autonomy="auto", threshold_key="locker_in_boot_switch", severity_ceiling="medium",
       confidence_floor=70, value_ceiling_gbp=3000, reversibility="reversible", blast_radius="region",
       sla_minutes=1440, consults=("transport", "sustainability"),
       approval_trigger="More than 40 engineers moved, or the switch is left standing beyond 14 days",
       executes="Moves the affected engineers onto overnight boot-drop from the next wave."),
    _a("vis.locker_provider_ticket", "Raise a locker-provider NOC ticket", module="/visibility", tab="Lockers",
       section="Pre-8AM Misses", category="execute", permission="read:field", agent="supplier",
       autonomy="auto", threshold_key="locker_provider_ticket", severity_ceiling="high",
       confidence_floor=65, reversibility="reversible", blast_radius="record", sla_minutes=30,
       consults=("supplier", "orchestrator"),
       approval_trigger="Escalating it to a contractual breach notice rather than a service ticket",
       executes="Logs the miss with the provider's NOC, starts the SLA clock and preserves the credit claim."),

    # ── 3 · TRANSPORT CONTROL ────────────────────────────────────────────────
    _a("trn.view_fleet", "Review the van fleet", module="/transport", tab="Vans",
       section="Fleet Status", category="observe", permission="read:field", agent="transport"),
    _a("trn.filter_fleet", "Filter the fleet (VOR · defects · EV)", module="/transport", tab="Vans",
       section="Fleet Status", category="observe", permission="read:field", agent="transport"),
    _a("trn.view_compliance", "Review DVSA walkaround compliance", module="/transport", tab="Compliance",
       section="Daily Walkarounds", category="observe", permission="read:field", agent="transport"),
    _a("trn.view_caz", "Review Clean Air Zone exposure", module="/transport", tab="Compliance",
       section="Clean Air Zones", category="observe", permission="read:field", agent="transport"),
    _a("trn.view_routes", "Review optimised engineer routes", module="/transport", tab="Routes",
       section="Route Optimisation", category="observe", permission="read:field", agent="transport"),
    _a("trn.view_drivers", "Review driver hours and assignments", module="/transport", tab="Drivers",
       section="Driver Roster", category="observe", permission="read:field", agent="transport"),
    _a("trn.complete_walkaround", "Record a DVSA walkaround", module="/transport", tab="Compliance",
       section="Daily Walkarounds", category="execute", permission="read:field", agent="transport",
       autonomy="human", threshold_key="complete_walkaround", severity_ceiling="medium",
       confidence_floor=99, reversibility="irreversible", blast_radius="record", sla_minutes=60,
       consults=("orchestrator",),
       why_human="A walkaround is a legal declaration by the named driver that they physically "
                 "inspected the vehicle. No agent may sign it — ATLAS may only chase it.",
       approval_trigger="Always — a driver must sign their own walkaround",
       executes="Records the walkaround against the vehicle and the signing driver."),
    _a("trn.walkaround_reminder", "Push a walkaround-due reminder", module="/transport", tab="Compliance",
       section="Daily Walkarounds", category="execute", permission="read:field", agent="transport",
       autonomy="auto", threshold_key="walkaround_reminder", severity_ceiling="medium",
       confidence_floor=65, reversibility="reversible", blast_radius="region", sla_minutes=30,
       consults=("orchestrator",),
       approval_trigger="Severity above medium (i.e. a compliance breach already occurred)",
       executes="Sends a walkaround-due push to every driver with no compliant record today."),
    _a("trn.resolve_defect", "Clear a vehicle defect and return it to service", module="/transport", tab="Vans",
       section="Fleet Status", category="execute", permission="read:field", agent="transport",
       autonomy="auto", threshold_key="resolve_defect", severity_ceiling="high",
       confidence_floor=72, reversibility="compensable", blast_radius="record", sla_minutes=120,
       consults=("orchestrator", "exception"),
       approval_trigger="A defect classed as major/safety-critical, or a second defect on the same van in 7 days",
       executes="Closes the defect record and returns the vehicle to available status."),
    _a("trn.resequence_run", "Re-sequence tonight's replenishment run", module="/transport", tab="Routes",
       section="Route Optimisation", category="execute", permission="read:field", agent="transport",
       autonomy="auto", threshold_key="resequence_run", severity_ceiling="medium",
       confidence_floor=65, reversibility="reversible", blast_radius="region", sla_minutes=180,
       consults=("replenishment", "visibility"),
       approval_trigger="Confidence < 65%, or the re-sequence drops any pre-8AM commitment",
       executes="Reorders tonight's van replenishment run by van-stock severity."),
    _a("trn.reassign_route", "Reassign a route to another engineer", module="/transport", tab="Routes",
       section="Route Optimisation", category="execute", permission="read:field", agent="transport",
       autonomy="human", threshold_key="reassign_route", severity_ceiling="high",
       confidence_floor=80, reversibility="compensable", blast_radius="region", sla_minutes=60,
       consults=("visibility", "orchestrator"),
       why_human="Reassignment changes a named person's working day and can breach driver-hours "
                 "rules. It needs a dispatcher who knows the crew.",
       approval_trigger="Always — it changes an individual's shift",
       executes="Moves the round to the nominated engineer and notifies both parties."),

    # 3a · Third-party carrier legs — hub → locker / in-boot / job site.
    # Bulky goods (outdoor units, cylinders, full boiler swaps) go two-man to the
    # customer address; everything else runs through the forward network.
    _a("trn.view_carriers", "Track third-party carrier movements", module="/transport", tab="Carriers",
       section="Carrier Movements", category="observe", permission="read:field", agent="transport",
       description="Every hub → locker / in-boot / job-site leg run by a third party, with live milestones."),
    _a("trn.book_carrier_movement", "Book a third-party carrier leg", module="/transport", tab="Carriers",
       section="Carrier Movements", category="execute", permission="write:transfer", agent="transport",
       autonomy="auto", threshold_key="carrier_book", severity_ceiling="medium",
       confidence_floor=70, value_ceiling_gbp=1200, commits_spend=True, reversibility="compensable",
       blast_radius="record", sla_minutes=240, consults=("visibility", "replenishment"),
       approval_trigger="Same-day or two-man service, or a leg over £1.2k — those are premium bookings",
       executes="Books the consignment with the routed carrier and starts milestone tracking."),
    _a("trn.carrier_escalate", "Escalate a late leg to the carrier", module="/transport", tab="Carriers",
       section="Carrier Delays", category="execute", permission="read:field", agent="transport",
       autonomy="auto", threshold_key="carrier_escalate", severity_ceiling="high",
       confidence_floor=65, reversibility="reversible", blast_radius="record", sla_minutes=30,
       consults=("supplier", "orchestrator"),
       approval_trigger="Escalating above the carrier's control tower to account management",
       executes="Raises the consignment with the carrier's control tower and pins a committed ETA.",
       description="Cheapest first move on a slip: make the incumbent recover it."),
    _a("trn.carrier_switch", "Re-book a leg with the backup carrier", module="/transport", tab="Carriers",
       section="Carrier Delays", category="execute", permission="write:transfer", agent="transport",
       autonomy="human", threshold_key="carrier_switch", severity_ceiling="high",
       confidence_floor=75, value_ceiling_gbp=2500, commits_spend=True, reversibility="compensable",
       blast_radius="region", sla_minutes=60, consults=("supplier", "replenishment", "orchestrator"),
       why_human="Switching carrier mid-consignment pays a second freight charge and puts a "
                 "contractual failure on record with the incumbent. That is a commercial act.",
       approval_trigger="Always — it commits a second freight charge and a supplier failure record",
       executes="Cancels the leg with the incumbent and re-books it under the standby agreement."),
    _a("trn.carrier_split", "Split critical lines to same-day", module="/transport", tab="Carriers",
       section="Carrier Delays", category="execute", permission="write:transfer", agent="transport",
       autonomy="human", threshold_key="carrier_split", severity_ceiling="high",
       confidence_floor=78, value_ceiling_gbp=1500, commits_spend=True, reversibility="compensable",
       blast_radius="record", sla_minutes=60, consults=("replenishment", "sustainability"),
       why_human="Premium same-day freight bought outside the plan, on a judgement about which lines "
                 "today's jobs genuinely need.",
       approval_trigger="Always — dedicated same-day is unplanned spend",
       executes="Books the critical lines onto a dedicated same-day leg and lets the balance run late."),
    _a("trn.carrier_divert", "Divert a leg to another drop-off", module="/transport", tab="Carriers",
       section="Carrier Delays", category="execute", permission="write:transfer", agent="transport",
       autonomy="auto", threshold_key="carrier_divert", severity_ceiling="high",
       confidence_floor=70, reversibility="reversible", blast_radius="record", sla_minutes=45,
       consults=("visibility",),
       approval_trigger="Detour over 25 miles, or a divert away from a customer address",
       executes="Changes the delivery point and moves the collecting engineer to meet it."),
    _a("trn.carrier_cover_from_hub", "Cover the job from hub stock instead", module="/transport", tab="Carriers",
       section="Carrier Delays", category="execute", permission="write:transfer", agent="replenishment",
       autonomy="auto", threshold_key="carrier_cover_from_hub", severity_ceiling="high",
       confidence_floor=72, value_ceiling_gbp=8000, reversibility="reversible", blast_radius="region",
       sla_minutes=120, consults=("replenishment", "visibility"),
       approval_trigger="Cover value over £8k, or the pull drops the hub below its own reorder point",
       executes="Covers the job from the nearest hub and demotes the late leg to replenishment."),
    _a("trn.carrier_rebook_job", "Rebook the appointment behind a late leg", module="/transport", tab="Carriers",
       section="Carrier Delays", category="execute", permission="write:exception", agent="transport",
       autonomy="human", threshold_key="carrier_rebook_job", severity_ceiling="high",
       confidence_floor=85, reversibility="compensable", blast_radius="record", sla_minutes=60,
       consults=("orchestrator",),
       why_human="Moving a customer's appointment is a promise being renegotiated. A person makes "
                 "that call and a person makes that phone call.",
       approval_trigger="Always — it renegotiates a customer commitment",
       executes="Moves the appointment to a slot the ETA supports and notifies the customer."),
    _a("trn.carrier_sla_claim", "Log a carrier SLA failure", module="/transport", tab="Carriers",
       section="Carrier Delays", category="execute", permission="read:field", agent="supplier",
       autonomy="auto", threshold_key="carrier_sla_claim", severity_ceiling="high",
       confidence_floor=65, reversibility="reversible", blast_radius="record", sla_minutes=1440,
       consults=("supplier",),
       approval_trigger="Raising it as a contractual breach rather than a logged failure",
       executes="Files the slip against the carrier's on-time SLA for recovery at the next rate review."),

    # 3b · Arrival risk — an engineer who will not make one or more windows.
    _a("trn.view_eta_risk", "Work the arrival-risk queue", module="/transport", tab="Routes",
       section="Arrival Risk", category="observe", permission="read:field", agent="transport",
       description="Rounds projected to miss a booked window, ranked by contractual exposure."),
    _a("trn.eta_reroute", "Re-optimise a late round", module="/transport", tab="Routes",
       section="Arrival Risk", category="execute", permission="read:field", agent="transport",
       autonomy="auto", threshold_key="eta_reroute", severity_ceiling="high",
       confidence_floor=70, reversibility="reversible", blast_radius="record", sla_minutes=15,
       consults=("visibility", "orchestrator"),
       approval_trigger="A re-sequence that drops any stop, or moves a confirmed customer window",
       executes="Re-sequences the remaining stops around live traffic and republishes the route."),
    _a("trn.eta_reallocate", "Reallocate an at-risk appointment", module="/transport", tab="Routes",
       section="Arrival Risk", category="execute", permission="write:transfer", agent="transport",
       autonomy="human", threshold_key="eta_reallocate", severity_ceiling="critical",
       confidence_floor=78, reversibility="compensable", blast_radius="region", sla_minutes=30,
       consults=("visibility", "orchestrator"),
       why_human="It changes two named people's working day, and the receiving engineer's own round "
                 "has to survive the addition.",
       approval_trigger="Always — it changes two individuals' shifts",
       executes="Moves the appointment onto the covering engineer's route and notifies both parties."),
    _a("trn.eta_notify_customer", "Send a revised arrival window", module="/transport", tab="Routes",
       section="Arrival Risk", category="execute", permission="read:field", agent="transport",
       autonomy="auto", threshold_key="eta_notify_customer", severity_ceiling="high",
       confidence_floor=65, reversibility="reversible", blast_radius="region", sla_minutes=10,
       consults=("orchestrator",),
       approval_trigger="More than 200 customers in one send, or a second re-window on the same job",
       executes="Pushes an updated arrival window to every affected customer before the original lapses.",
       description="A warned customer is not a complaint. Cheapest protection when the minutes are gone."),
    _a("trn.eta_defer_stop", "Defer a non-SLA stop", module="/transport", tab="Routes",
       section="Arrival Risk", category="execute", permission="write:exception", agent="transport",
       autonomy="human", threshold_key="eta_defer_stop", severity_ceiling="high",
       confidence_floor=80, reversibility="compensable", blast_radius="record", sla_minutes=30,
       consults=("orchestrator",),
       why_human="Deferring is choosing which customer is disappointed. That choice belongs to a person.",
       approval_trigger="Always — it stands a customer down",
       executes="Takes the stop off today's round and queues it for rebooking."),
    _a("trn.eta_overtime", "Authorise overtime on a round", module="/transport", tab="Routes",
       section="Arrival Risk", category="execute", permission="write:transfer", agent="transport",
       autonomy="human", threshold_key="eta_overtime", severity_ceiling="high",
       confidence_floor=85, value_ceiling_gbp=500, commits_spend=True, reversibility="irreversible",
       blast_radius="record", sla_minutes=30, consults=("orchestrator",),
       why_human="Extending a named person's duty day is an employment matter bounded by drivers' "
                 "hours. No agent extends anybody's shift.",
       approval_trigger="Always — it is paid time and a longer duty day for a named person",
       executes="Authorises the overtime and retains every remaining stop on today's round."),
    _a("trn.eta_escalate", "Escalate an arrival breach", module="/transport", tab="Routes",
       section="Arrival Risk", category="execute", permission="write:exception", agent="exception",
       autonomy="human", threshold_key="eta_escalate", severity_ceiling="critical",
       confidence_floor=80, reversibility="reversible", blast_radius="record", sla_minutes=15,
       consults=("exception", "orchestrator"),
       why_human="Escalation puts a breach on the incident record with a named owner. Declaring one "
                 "is a duty-manager act, not a background one.",
       approval_trigger="Always — it opens a tracked incident",
       executes="Raises an arrival-risk exception and pages the duty manager."),

    # ── 4 · DEMAND & INVENTORY ───────────────────────────────────────────────
    # 4a · Planner Worklist
    _a("dmd.view_worklist", "Work the prioritised planner worklist", module="/demand", tab="Planner Worklist",
       section="Worklist", category="observe", permission="write:po", agent="replenishment",
       description="One ranked queue across replenish / redistribute / reduce / de-risk."),
    _a("dmd.filter_worklist", "Filter the worklist by family, kind or SLA", module="/demand", tab="Planner Worklist",
       section="Worklist", category="observe", permission="write:po", agent="replenishment"),
    # 4b · Inventory optimisation
    _a("dmd.view_inventory", "Search and page the inventory positions", module="/demand", tab="Inventory optimisation",
       section="Inventory Positions", category="observe", permission="write:po", agent="replenishment"),
    _a("dmd.scope_site", "Switch stock scope (network ↔ NDC ↔ hub)", module="/demand", tab="Inventory optimisation",
       section="Network Flow", category="observe", permission="write:po", agent="replenishment"),
    _a("dmd.segment_filter", "Narrow by ABC/XYZ segment or category", module="/demand", tab="Inventory optimisation",
       section="Segmentation", category="observe", permission="write:po", agent="replenishment"),
    _a("dmd.sku_drill", "Open a SKU's position, site split and demand chart", module="/demand", tab="Inventory optimisation",
       section="Inventory Positions", category="observe", permission="write:po", agent="replenishment"),
    _a("dmd.view_meio", "Review multi-echelon risk pooling (MEIO)", module="/demand", tab="Inventory optimisation",
       section="MEIO", category="analyse", permission="write:po", agent="replenishment"),
    _a("dmd.view_forecast_tuning", "Review forecast bias and buffer-policy nudges", module="/demand", tab="Inventory optimisation",
       section="Forecast Tuning", category="analyse", permission="write:po", agent="replenishment"),
    _a("dmd.generate_forecast", "Generate a SKU forecast over a horizon", module="/demand", tab="Inventory optimisation",
       section="Forecast & Quality", category="analyse", permission="write:po", agent="demand_sensing",
       autonomy="auto", threshold_key="generate_forecast", severity_ceiling="opportunity",
       confidence_floor=55, reversibility="reversible", blast_radius="record",
       consults=("replenishment",),
       approval_trigger="Never — a forecast is an analysis, not a commitment",
       executes="Runs the causal forecast for the SKU and stores it against the position."),
    _a("dmd.tune_buffer_policy", "Apply a buffer-policy change to a SKU", module="/demand", tab="Inventory optimisation",
       section="Forecast Tuning", category="execute", permission="write:po", agent="replenishment",
       autonomy="auto", threshold_key="tune_buffer_policy", severity_ceiling="medium",
       confidence_floor=75, value_ceiling_gbp=20000, reversibility="reversible", blast_radius="record",
       sla_minutes=1440, consults=("demand_sensing", "supplier"),
       approval_trigger="Working-capital impact over £20k, or a cut to safety stock on an A-class SKU",
       executes="Adjusts the SKU's safety stock and reorder point to the tuned policy."),
    # 4c · Replenishment & fulfilment
    _a("dmd.raise_po_standard", "Raise a standard purchase order", module="/demand", tab="Replenishment & fulfilment",
       section="Replenishment Orders", category="execute", permission="write:po", agent="replenishment",
       autonomy="auto", threshold_key="raise_po_standard", severity_ceiling="medium",
       confidence_floor=70, value_ceiling_gbp=25000, commits_spend=True, reversibility="compensable", blast_radius="site",
       sla_minutes=1440, consults=("supplier", "demand_sensing", "transport"),
       approval_trigger="Order value over £25k, severity above medium, confidence under 70%, "
                        "or the supplier carries a financial-health flag",
       executes="Raises a standard PO on the routed supplier into the NDC.",
       description="Cover an amber position before it turns red, at normal lead time and cost."),
    _a("dmd.raise_po_emergency", "Raise an emergency purchase order", module="/demand", tab="Replenishment & fulfilment",
       section="Replenishment Orders", category="execute", permission="write:po", agent="replenishment",
       autonomy="human", threshold_key="raise_po_emergency", severity_ceiling="critical",
       confidence_floor=90, commits_spend=True, reversibility="compensable", blast_radius="network", sla_minutes=120,
       consults=("supplier", "transport", "sustainability", "orchestrator"),
       why_human="Emergency orders carry a freight premium and commit unplanned spend. The cost "
                 "trade-off against a failed first visit is a commercial judgement.",
       approval_trigger="Always — premium freight is unplanned spend",
       executes="Raises an EMERGENCY PO with expedited freight on the routed supplier."),
    _a("dmd.expedite_po", "Expedite an in-flight purchase order", module="/demand", tab="Replenishment & fulfilment",
       section="Replenishment Orders", category="execute", permission="write:po", agent="replenishment",
       autonomy="auto", threshold_key="expedite_po", severity_ceiling="high",
       confidence_floor=72, value_ceiling_gbp=10000, commits_spend=True, reversibility="compensable", blast_radius="site",
       sla_minutes=240, consults=("supplier", "transport", "sustainability"),
       approval_trigger="Expedite premium over £10k, or the supplier is already on the OTIF watch-list",
       executes="Pulls the PO forward to the fastest available delivery."),
    _a("dmd.receive_po", "Receipt a delivered purchase order", module="/demand", tab="Replenishment & fulfilment",
       section="Replenishment Orders", category="execute", permission="write:po", agent="replenishment",
       autonomy="human", threshold_key="receive_po", severity_ceiling="low",
       confidence_floor=95, reversibility="irreversible", blast_radius="site", sla_minutes=120,
       consults=("supplier",),
       why_human="Goods receipt triggers payment and asserts physical possession. It must follow a "
                 "physical count, so it stays with the goods-in team.",
       approval_trigger="Always — receipt asserts physical possession and releases payment",
       executes="Books the PO in, increments on-hand and closes the order."),
    _a("dmd.raise_transfer", "Raise a stock transfer (STO)", module="/demand", tab="Replenishment & fulfilment",
       section="Stock Transfers", category="execute", permission="write:po", agent="replenishment",
       autonomy="auto", threshold_key="raise_transfer", severity_ceiling="high",
       confidence_floor=68, value_ceiling_gbp=75000, reversibility="reversible", blast_radius="region",
       sla_minutes=480, consults=("transport", "visibility"),
       approval_trigger="Transfer value over £75k, or a move that would push the source site below its own safety stock",
       description="A transfer commits no new spend — it relocates stock the business already owns, and "
                   "it can be moved back. Its ceiling is therefore set far above a purchase order's: the "
                   "guardrail here exists to stop one move stranding a donor site, not to cap value.",
       executes="Raises a trunker STO from the supplying site to the requesting site."),
    _a("dmd.receive_transfer", "Receipt an arrived transfer", module="/demand", tab="Replenishment & fulfilment",
       section="Stock Transfers", category="execute", permission="write:po", agent="replenishment",
       autonomy="human", threshold_key="receive_transfer", severity_ceiling="low",
       confidence_floor=95, reversibility="irreversible", blast_radius="site", sla_minutes=120,
       consults=("transport",),
       why_human="Same as a goods receipt — it asserts physical possession at the receiving site.",
       approval_trigger="Always — receipt asserts physical possession",
       executes="Books the transfer in at the destination and closes the STO."),
    _a("dmd.rebalance_hubs", "Rebalance stock laterally between hubs", module="/demand", tab="Replenishment & fulfilment",
       section="Stock Transfers", category="execute", permission="write:po", agent="replenishment",
       autonomy="auto", threshold_key="rebalance_hubs", severity_ceiling="high",
       confidence_floor=70, value_ceiling_gbp=15000, reversibility="reversible", blast_radius="region",
       sla_minutes=480, consults=("transport", "visibility", "sustainability"),
       approval_trigger="Value over £15k, or the move strands the donor hub below its reorder point",
       executes="Moves surplus units hub → hub on the next trunker leg."),
    # 4d · Excess & disposition
    _a("dmd.create_disposition", "Flag excess stock for disposition", module="/demand", tab="Inventory optimisation",
       section="Excess & Disposition", category="execute", permission="write:po", agent="replenishment",
       autonomy="auto", threshold_key="create_disposition", severity_ceiling="opportunity",
       confidence_floor=65, value_ceiling_gbp=150000, reversibility="reversible", blast_radius="site",
       sla_minutes=4320, consults=("sustainability", "orchestrator"),
       approval_trigger="Recoverable value over £150k, or the disposition is scrap rather than rebalance",
       executes="Raises an excess disposition for the inventory analyst to action."),
    _a("dmd.apply_all_dispositions", "Apply every recommended disposition", module="/demand", tab="Inventory optimisation",
       section="Excess & Disposition", category="execute", permission="write:po", agent="replenishment",
       autonomy="dual", threshold_key="apply_all_dispositions", severity_ceiling="opportunity",
       confidence_floor=85, value_ceiling_gbp=0, reversibility="irreversible", blast_radius="network",
       sla_minutes=4320, consults=("sustainability", "supplier", "orchestrator"),
       why_human="A bulk disposition writes down stock across the whole network in one action. "
                 "It is irreversible and lands in the P&L, so it takes two approvers.",
       approval_trigger="Always — plus a second approver above the dual-control line (£100k)",
       executes="Applies every open disposition recommendation across the network."),
    # 4e · S&OP, allocation & the network twin
    _a("dmd.view_sop", "Review the S&OP plan", module="/demand", tab="S&OP, allocation & the network twin",
       section="S&OP", category="analyse", permission="write:po", agent="replenishment"),
    _a("dmd.view_dependent_demand", "Review dependent demand over a horizon", module="/demand", tab="S&OP, allocation & the network twin",
       section="Dependent Demand", category="analyse", permission="write:po", agent="demand_sensing"),
    _a("dmd.simulate_network", "Run a network what-if simulation", module="/demand", tab="S&OP, allocation & the network twin",
       section="Network Twin", category="analyse", permission="write:po", agent="replenishment",
       autonomy="auto", threshold_key="simulate_network", severity_ceiling="opportunity",
       confidence_floor=55, reversibility="reversible", blast_radius="network",
       consults=("demand_sensing", "supplier"),
       approval_trigger="Never — the twin is a sandbox and touches no live state",
       executes="Runs the demand-shock / lead-slip simulation against a copy of live state."),
    _a("dmd.view_financials", "Review the working-capital lens", module="/demand", tab="S&OP, allocation & the network twin",
       section="Financials", category="analyse", permission="read:finance", agent="replenishment"),
    _a("dmd.view_programmes", "Review programme & policy drivers", module="/demand", tab="Programme & Policy Drivers",
       section="Programmes", category="observe", permission="write:po", agent="demand_sensing"),

    # ── 5 · IoT & SMART TECH ─────────────────────────────────────────────────
    _a("iot.view_fault_pipeline", "Review the boiler fault pipeline", module="/iot", tab="Boiler Fault Pipeline",
       section="Fault Pipeline", category="observe", permission="read:field", agent="demand_sensing"),
    _a("iot.view_predictive", "Review predictive replacement candidates", module="/iot", tab="Predictive Replacements",
       section="Predictive Replacements", category="observe", permission="read:field", agent="demand_sensing"),
    _a("iot.view_smart_meter", "Review the smart-meter rollout", module="/iot", tab="Smart Meter Rollout",
       section="Smart Meter Rollout", category="observe", permission="read:field", agent="demand_sensing"),
    _a("iot.pre_position", "Pre-position parts ahead of predicted demand", module="/iot", tab="Boiler Fault Pipeline",
       section="Demand Sensing", category="execute", permission="write:po", agent="demand_sensing",
       autonomy="auto", threshold_key="pre_position", severity_ceiling="high",
       confidence_floor=68, value_ceiling_gbp=40000, commits_spend=True, reversibility="reversible", blast_radius="region",
       sla_minutes=720, consults=("replenishment", "transport", "visibility"),
       approval_trigger="Pre-position value over £40k, or the move is driven by a single weather model run",
       executes="Moves condensate and diverter-valve stock to the coldest-region hubs."),
    _a("iot.proactive_outreach", "Queue proactive customer outreach", module="/iot", tab="Predictive Replacements",
       section="Proactive Outreach", category="execute", permission="read:field", agent="demand_sensing",
       autonomy="auto", threshold_key="proactive_outreach", severity_ceiling="medium",
       confidence_floor=68, reversibility="reversible", blast_radius="region", sla_minutes=1440,
       consults=("orchestrator",),
       approval_trigger="Confidence < 68%, or the campaign exceeds 5,000 households",
       executes="Queues outreach to the highest-risk Hive-flagged properties."),
    _a("iot.schedule_replacement", "Convert a predictive signal into a booked replacement", module="/iot",
       tab="Predictive Replacements", section="Predictive Replacements", category="execute",
       permission="read:field", agent="demand_sensing",
       autonomy="human", threshold_key="schedule_replacement", severity_ceiling="high",
       confidence_floor=85, reversibility="compensable", blast_radius="record", sla_minutes=2880,
       consults=("replenishment", "transport"),
       why_human="Booking a replacement commits an engineer, an asset and a customer appointment. "
                 "It is a customer-facing commercial commitment.",
       approval_trigger="Always — it commits a customer appointment and an asset",
       executes="Books the replacement job and reserves the asset against it."),

    # ── 6 · SUSTAINABILITY ───────────────────────────────────────────────────
    _a("sus.view_reverse", "Review the reverse-logistics pipeline", module="/sustainability", tab="Reverse Logistics",
       section="Reverse Pipeline", category="observe", permission="read:reverse", agent="sustainability"),
    _a("sus.view_weee", "Review WEEE compliance status", module="/sustainability", tab="WEEE Compliance",
       section="WEEE", category="observe", permission="read:sustainability", agent="sustainability"),
    _a("sus.view_scope3", "Review Scope 3 emissions", module="/sustainability", tab="Scope 3 Emissions",
       section="Scope 3", category="observe", permission="read:sustainability", agent="sustainability"),
    _a("sus.collection_sweep", "Schedule a consolidated collection sweep", module="/sustainability", tab="Reverse Logistics",
       section="Reverse Pipeline", category="execute", permission="read:reverse", agent="sustainability",
       autonomy="auto", threshold_key="collection_sweep", severity_ceiling="high",
       confidence_floor=65, reversibility="reversible", blast_radius="region", sla_minutes=2880,
       consults=("transport", "visibility"),
       approval_trigger="Confidence < 65%, or the sweep needs a vehicle outside the standing contract",
       executes="Schedules a consolidated reverse-logistics collection for the pending backlog."),
    _a("sus.log_decommission", "Log a decommissioned unit", module="/sustainability", tab="Reverse Logistics",
       section="Decommission Log", category="execute", permission="read:reverse", agent="sustainability",
       autonomy="human", threshold_key="log_decommission", severity_ceiling="low",
       confidence_floor=95, reversibility="irreversible", blast_radius="record", sla_minutes=1440,
       consults=("orchestrator",),
       why_human="The decommission log is the WEEE chain-of-custody record. The engineer who removed "
                 "the unit signs it; a false entry is a regulatory breach.",
       approval_trigger="Always — it is a regulated chain-of-custody entry",
       executes="Writes the decommission record against the job and the asset."),
    _a("sus.consolidate_returns", "Consolidate return routes to cut empty miles", module="/sustainability",
       tab="Scope 3 Emissions", section="Scope 3", category="execute", permission="read:reverse",
       agent="sustainability", autonomy="auto", threshold_key="consolidate_returns",
       severity_ceiling="medium", confidence_floor=65, reversibility="reversible", blast_radius="region",
       sla_minutes=2880, consults=("transport",),
       approval_trigger="Confidence < 65%, or consolidation delays any WEEE-critical collection past its deadline",
       executes="Merges return legs onto existing outbound routes and republishes the plan."),

    # ── 7 · EXCEPTIONS ───────────────────────────────────────────────────────
    _a("exc.view_exceptions", "Review the open exception queue", module="/exceptions", tab="Operational Alerts",
       section="Exception Queue", category="observe", permission="write:exception", agent="exception"),
    _a("exc.filter_exceptions", "Filter exceptions by priority or status", module="/exceptions", tab="Operational Alerts",
       section="Exception Queue", category="observe", permission="write:exception", agent="exception"),
    _a("exc.view_playbook", "Read an exception's AI response playbook", module="/exceptions", tab="AI Response Playbooks",
       section="Playbooks", category="observe", permission="write:exception", agent="exception"),
    _a("exc.acknowledge", "Acknowledge and own an exception", module="/exceptions", tab="Operational Alerts",
       section="Exception Queue", category="execute", permission="write:exception", agent="exception",
       autonomy="auto", threshold_key="acknowledge", severity_ceiling="critical",
       confidence_floor=70, reversibility="reversible", blast_radius="record", sla_minutes=30,
       consults=("orchestrator",),
       approval_trigger="Never — acknowledgement is triage, not a decision. What it stages "
                        "(the response plan) is always human.",
       description="Auto-triage: no incident should ever sit unowned with its SLA clock stopped. "
                   "Acknowledging assigns it and starts the clock; it decides nothing and commits "
                   "nothing, and the plan behind it still needs a human.",
       executes="Acknowledges the exception, starts its resolution clock and pages the domain owner."),
    _a("exc.activate_plan", "Activate an exception's response plan", module="/exceptions", tab="AI Response Playbooks",
       section="Playbooks", category="execute", permission="write:exception", agent="exception",
       autonomy="human", threshold_key="activate_plan", severity_ceiling="medium",
       confidence_floor=80, reversibility="compensable", blast_radius="network", sla_minutes=15,
       consults=("replenishment", "transport", "visibility", "supplier", "orchestrator"),
       why_human="Plan activation fires compensating actions across several modules at once — "
                 "failovers, reroutes, emergency orders. That commitment is the duty manager's.",
       approval_trigger="Always — it commits cross-module compensating action",
       executes="Activates the staged response plan and acknowledges the exception."),
    _a("exc.resolve", "Resolve an exception with a root cause", module="/exceptions", tab="Resolution Tracking",
       section="Resolution", category="execute", permission="write:exception", agent="exception",
       autonomy="human", threshold_key="resolve_exception", severity_ceiling="low",
       confidence_floor=85, reversibility="irreversible", blast_radius="record", sla_minutes=60,
       consults=("orchestrator",),
       why_human="Closing an incident asserts the underlying fault is genuinely fixed and files the "
                 "root cause. A premature close hides a repeat failure.",
       approval_trigger="Always — closure asserts the fault is genuinely fixed",
       executes="Closes the exception with the stated root cause and resolution notes."),
    _a("exc.update_alert_rule", "Tune an alert rule threshold", module="/exceptions", tab="Operational Alerts",
       section="Alert Rules", category="govern", permission="write:exception", agent="exception",
       autonomy="human", threshold_key="update_alert_rule", severity_ceiling="medium",
       confidence_floor=85, reversibility="reversible", blast_radius="network", sla_minutes=1440,
       consults=("orchestrator",),
       why_human="Loosening a threshold suppresses future alerts network-wide. Only a human should "
                 "decide the business is willing to stop being told.",
       approval_trigger="Always — it changes what the network will be told about in future",
       executes="Updates the alert rule's threshold and re-arms it."),
    _a("exc.escalate_p1", "Declare a P1 incident", module="/exceptions", tab="Operational Alerts",
       section="Exception Queue", category="execute", permission="write:exception", agent="exception",
       autonomy="human", threshold_key="escalate_p1", severity_ceiling="critical",
       confidence_floor=90, reversibility="compensable", blast_radius="network", sla_minutes=5,
       consults=("orchestrator", "visibility", "transport"),
       why_human="A P1 wakes executives and starts a formal incident. Declaring one is a leadership act.",
       approval_trigger="Always — a P1 declaration mobilises the business",
       executes="Raises the exception to P1, fires the banner and pages the incident chain."),

    # ── 8 · SCENARIO SIMULATOR ───────────────────────────────────────────────
    _a("sim.view_scenarios", "Browse the scenario library", module="/simulator", tab="Scenario Library",
       section="Scenarios", category="observe", permission="write:exception", agent="orchestrator"),
    _a("sim.run_scenario", "Simulate a risk scenario", module="/simulator", tab="Scenario Library",
       section="Scenarios", category="analyse", permission="write:exception", agent="orchestrator",
       autonomy="human", threshold_key="run_scenario", severity_ceiling="critical",
       confidence_floor=99, reversibility="reversible", blast_radius="network", sla_minutes=None,
       consults=("orchestrator",),
       why_human="A simulation rewrites the whole demonstration environment for every logged-in user. "
                 "It is a deliberate act, never a background one.",
       approval_trigger="Always — it rewrites shared state for every user",
       executes="Applies the scenario across every module and broadcasts to all sessions."),
    _a("sim.reset_baseline", "Reset the network to baseline", module="/simulator", tab="Scenario Library",
       section="Scenarios", category="analyse", permission="write:exception", agent="orchestrator",
       autonomy="human", threshold_key="reset_baseline", severity_ceiling="critical",
       confidence_floor=99, reversibility="irreversible", blast_radius="network",
       consults=("orchestrator",),
       why_human="Reset discards every in-flight mutation, including work other users are mid-way through.",
       approval_trigger="Always — it discards in-flight work",
       executes="Rebuilds the baseline snapshot and clears the active scenario."),
    _a("sim.model_disruption", "Model a disruption's financial impact", module="/simulator", tab="Scenario Library",
       section="Impact Modelling", category="analyse", permission="write:exception", agent="orchestrator",
       autonomy="auto", threshold_key="model_disruption", severity_ceiling="opportunity",
       confidence_floor=55, reversibility="reversible", blast_radius="network",
       consults=("replenishment", "supplier", "transport"),
       approval_trigger="Never — modelling touches no live state",
       executes="Runs the disruption model and returns the projected impact."),

    # ── 9 · SUPPLIER & LABOUR RISK ───────────────────────────────────────────
    _a("rsk.view_scorecards", "Review supplier scorecards", module="/risk", tab="Supplier Scorecards",
       section="Scorecards", category="observe", permission="read:suppliers", agent="supplier"),
    _a("rsk.sort_suppliers", "Sort or filter the supplier portfolio", module="/risk", tab="Supplier Scorecards",
       section="Scorecards", category="observe", permission="read:suppliers", agent="supplier"),
    _a("rsk.view_supplier_detail", "Open a supplier's 12-week OTIF history", module="/risk", tab="Supplier Scorecards",
       section="Scorecards", category="observe", permission="read:suppliers", agent="supplier"),
    _a("rsk.view_labour", "Review warehouse labour risk", module="/risk", tab="Labour Risk",
       section="Labour Assessment", category="observe", permission="read:suppliers", agent="supplier"),
    _a("rsk.view_labour_history", "Open a site's labour-risk history", module="/risk", tab="Labour Risk",
       section="Labour Assessment", category="observe", permission="read:suppliers", agent="supplier"),
    _a("rsk.view_warehouse_health", "Review 3PL warehouse health", module="/risk", tab="Warehouse Health",
       section="Warehouse Health", category="observe", permission="read:suppliers", agent="supplier"),
    _a("rsk.otif_watchlist", "Add a supplier to the OTIF watch-list", module="/risk", tab="Supplier Scorecards",
       section="Scorecards", category="execute", permission="write:supplier_review", agent="supplier",
       autonomy="auto", threshold_key="otif_watchlist", severity_ceiling="medium",
       confidence_floor=68, reversibility="reversible", blast_radius="record", sla_minutes=2880,
       consults=("replenishment", "orchestrator"),
       approval_trigger="Severity above medium — a tier-1 supplier's watch-listing is commercially visible",
       executes="Places the supplier on the active OTIF watch-list with weekly reporting."),
    _a("rsk.supplier_review", "Open a supplier contingency review", module="/risk", tab="Supplier Scorecards",
       section="Scorecards", category="execute", permission="write:supplier_review", agent="supplier",
       autonomy="human", threshold_key="supplier_review", severity_ceiling="high",
       confidence_floor=80, reversibility="compensable", blast_radius="network", sla_minutes=480,
       consults=("replenishment", "orchestrator"),
       why_human="A contingency review freezes new commitments with a trading partner. That is a "
                 "commercial and relationship decision with contractual consequences.",
       approval_trigger="Always — it freezes commitments with a trading partner",
       executes="Opens the contingency review and freezes new commitments with the supplier."),
    _a("rsk.dual_source", "Initiate dual-sourcing for a category", module="/risk", tab="Supplier Scorecards",
       section="Scorecards", category="execute", permission="write:supplier_review", agent="supplier",
       autonomy="dual", threshold_key="dual_source", severity_ceiling="high",
       confidence_floor=85, commits_spend=True, reversibility="irreversible", blast_radius="network", sla_minutes=10080,
       consults=("replenishment", "sustainability", "orchestrator"),
       why_human="Dual-sourcing rewrites the supply base for a category — a procurement strategy "
                 "decision with multi-year contract consequences.",
       approval_trigger="Always — plus a second approver (procurement director)",
       executes="Opens a dual-source workstream and issues RFQs to alternate suppliers."),
    _a("rsk.labour_escalation", "Escalate a site's labour risk to HR", module="/risk", tab="Labour Risk",
       section="Labour Assessment", category="execute", permission="write:supplier_review", agent="supplier",
       autonomy="human", threshold_key="labour_escalation", severity_ceiling="high",
       confidence_floor=80, reversibility="reversible", blast_radius="site", sla_minutes=1440,
       consults=("orchestrator",),
       why_human="Labour and union matters involve named people and employment law. No agent acts here.",
       approval_trigger="Always — employee relations is never automated",
       executes="Raises a labour-risk escalation to the HR business partner for the site."),

    # ── 10 · AI COMMAND CENTER ───────────────────────────────────────────────
    _a("ai.view_command_center", "Read the ATLAS command centre", module="/ai", tab="Command Center",
       section="Overview", category="observe", permission="read:analytics", agent="orchestrator"),
    _a("ai.approve_recommendation", "Approve a recommendation", module="/ai", tab="Approvals",
       section="Approval Queue", category="govern", permission="write:po", agent="orchestrator",
       autonomy="human", threshold_key="approve_recommendation", severity_ceiling="critical",
       confidence_floor=99, reversibility="compensable", blast_radius="network", sla_minutes=60,
       consults=("orchestrator",),
       why_human="The approval itself is the human control point. ATLAS can never approve its own work.",
       approval_trigger="Always — this IS the human control point",
       executes="Executes the underlying action the recommendation carries."),
    _a("ai.dismiss_recommendation", "Dismiss a recommendation with a reason", module="/ai", tab="Approvals",
       section="Approval Queue", category="govern", permission="write:po", agent="orchestrator",
       autonomy="human", threshold_key="dismiss_recommendation", severity_ceiling="critical",
       confidence_floor=99, reversibility="reversible", blast_radius="record", sla_minutes=60,
       consults=("orchestrator",),
       why_human="Overriding ATLAS is a human prerogative, and the reason is training signal.",
       approval_trigger="Always — an override is a human act",
       executes="Dismisses the recommendation and logs the reason to the audit trail."),
    _a("ai.bulk_approve", "Bulk-approve a filtered set of recommendations", module="/ai", tab="Approvals",
       section="Approval Queue", category="govern", permission="write:po", agent="orchestrator",
       autonomy="human", threshold_key="bulk_approve", severity_ceiling="medium",
       confidence_floor=99, value_ceiling_gbp=100000, reversibility="compensable", blast_radius="network",
       sla_minutes=60, consults=("orchestrator",),
       why_human="Bulk approval multiplies a single click across many commitments — it needs an "
                 "explicit human act and is capped at the dual-control line.",
       approval_trigger="Always; blocked entirely above £100k combined value or any critical row",
       executes="Approves every selected recommendation in order of severity."),
    _a("ai.view_automated", "Review what ATLAS automated in 24h", module="/ai", tab="Automated · 24h",
       section="Automated Actions", category="observe", permission="read:analytics", agent="orchestrator"),
    _a("ai.view_capabilities", "Review the capability roster", module="/ai", tab="Capabilities",
       section="Capabilities", category="observe", permission="read:analytics", agent="orchestrator"),
    _a("ai.view_audit", "Search the decision & action audit trail", module="/ai", tab="Audit Log",
       section="Audit", category="observe", permission="read:analytics", agent="orchestrator"),
    _a("ai.view_trace", "Open an action's reasoning trace", module="/ai", tab="Audit Log",
       section="Audit", category="observe", permission="read:analytics", agent="orchestrator",
       description="The full stack: signals sensed, reasoning steps, cross-agent negotiation, "
                   "arbitration and the final decision."),
    _a("ai.ask", "Ask ATLAS a grounded question", module="/ai", tab="Ask ATLAS",
       section="Ask Console", category="analyse", permission="read:analytics", agent="orchestrator",
       autonomy="auto", threshold_key="ask_atlas", severity_ceiling="opportunity",
       confidence_floor=50, reversibility="reversible", blast_radius="record",
       approval_trigger="Never — answering reads state, it does not change it",
       executes="Answers from live control-tower state."),
    _a("ai.set_agent_autonomy", "Change a capability's autonomy level", module="/ai", tab="Capabilities",
       section="Capabilities", category="govern", permission="write:po", agent="orchestrator",
       autonomy="human", threshold_key="set_agent_autonomy", severity_ceiling="critical",
       confidence_floor=99, reversibility="reversible", blast_radius="network", sla_minutes=None,
       consults=("orchestrator",),
       why_human="Self-granting autonomy is the one thing an agent must never do.",
       approval_trigger="Always — ATLAS may never widen its own mandate",
       executes="Sets the capability to manual, semi or auto."),
    _a("ai.set_guardrails", "Change the spend guardrails", module="/ai", tab="Governance",
       section="Guardrails", category="govern", permission="write:po", agent="orchestrator",
       autonomy="dual", threshold_key="set_guardrails", severity_ceiling="critical",
       confidence_floor=99, reversibility="reversible", blast_radius="network",
       consults=("orchestrator",),
       why_human="Guardrails are the spend limits on autonomy itself. Raising them takes two people.",
       approval_trigger="Always — plus a second approver to raise any ceiling",
       executes="Updates the auto-approve, dual-control and spend-ceiling limits."),
    _a("ai.create_watch_rule", "Author a no-code watch rule", module="/ai", tab="Governance",
       section="Watch Rules", category="govern", permission="write:po", agent="custom",
       autonomy="human", threshold_key="create_watch_rule", severity_ceiling="critical",
       confidence_floor=99, reversibility="reversible", blast_radius="network",
       consults=("orchestrator",),
       why_human="A watch rule defines what the business considers worth waking up for.",
       approval_trigger="Always — the operator authors their own thresholds",
       executes="Creates the rule and begins evaluating it against live state."),
    _a("ai.delete_watch_rule", "Delete a watch rule", module="/ai", tab="Governance",
       section="Watch Rules", category="govern", permission="write:po", agent="custom",
       autonomy="human", threshold_key="delete_watch_rule", severity_ceiling="critical",
       confidence_floor=99, reversibility="reversible", blast_radius="network",
       consults=("orchestrator",),
       why_human="Deleting a rule blinds the tower to something an operator chose to watch.",
       approval_trigger="Always — removing a watch is a deliberate act",
       executes="Removes the rule and stops evaluating it."),
    _a("ai.custom_rule_ack", "Acknowledge a watch-rule breach", module="/ai", tab="Approvals",
       section="Approval Queue", category="execute", permission="read:field", agent="custom",
       autonomy="human", threshold_key="custom_rule_ack", severity_ceiling="critical",
       confidence_floor=55, reversibility="reversible", blast_radius="record", sla_minutes=120,
       consults=("orchestrator",),
       why_human="The operator authored this threshold precisely because they wanted to be told. "
                 "Auto-acknowledging it would defeat the point of writing it.",
       approval_trigger="Always — the operator asked to be told",
       executes="Logs the breach and notifies the domain owner."),
    _a("ai.toggle_ai_mode", "Turn ATLAS on or off", module="/ai", tab="Command Center",
       section="Master Switch", category="govern", permission="read:analytics", agent="orchestrator",
       autonomy="human", threshold_key="toggle_ai_mode", severity_ceiling="critical",
       confidence_floor=99, reversibility="reversible", blast_radius="network",
       consults=("orchestrator",),
       why_human="The master switch is the operator's kill switch. It is theirs alone.",
       approval_trigger="Always — the kill switch belongs to the human",
       executes="Enables or disables the whole agentic layer for this environment."),

    # ── 11 · PLATFORM & SESSION ──────────────────────────────────────────────
    _a("plt.login", "Sign in", module="/platform", tab="Session", section="Authentication",
       category="govern", autonomy="human", threshold_key="platform_login",
       confidence_floor=99, reversibility="reversible", blast_radius="record",
       why_human="Authentication is the identity boundary — never delegated.",
       approval_trigger="Always — identity is never delegated",
       executes="Authenticates the user and issues a session token."),
    _a("plt.logout", "Sign out", module="/platform", tab="Session", section="Authentication",
       category="govern", autonomy="human", threshold_key="platform_logout",
       confidence_floor=99, reversibility="reversible", blast_radius="record",
       why_human="Ending a session is the user's own act.",
       approval_trigger="Always", executes="Clears the session and returns to sign-in."),
    _a("plt.switch_theme", "Switch light/dark theme", module="/platform", tab="Preferences",
       section="Appearance", category="observe", agent="orchestrator"),
    _a("plt.open_guide", "Open the user guide or video tour", module="/platform", tab="Help",
       section="Guidance", category="observe", agent="orchestrator"),
    _a("plt.contact_support", "Contact support", module="/platform", tab="Help",
       section="Support", category="observe", agent="orchestrator"),
]

ACTION_BY_KEY = {a["key"]: a for a in ACTION_CATALOG}
ACTION_BY_THRESHOLD = {a["threshold_key"]: a for a in ACTION_CATALOG if a.get("threshold_key")}


# ── Derived: the policy the agent engine actually enforces ────────────────────
# Kept in the exact shape the engine has always consumed, so the catalog above
# is the only place a threshold is ever edited.
def _thresholds() -> dict:
    out = {}
    for a in ACTION_CATALOG:
        tk = a.get("threshold_key")
        if not tk:
            continue
        out[tk] = {
            "label": a["label"],
            # The engine understands auto vs. escalate; dual-control is a stricter
            # human class, so it maps to "human" plus the dual_control flag.
            "autonomy": "auto" if a["autonomy"] == "auto" else "human",
            "value_ceiling_gbp": a["value_ceiling_gbp"],
            "commits_spend": a["commits_spend"],
            "severity_ceiling": a["severity_ceiling"],
            "confidence_floor": a["confidence_floor"],
            "dual_control": a["autonomy"] == "dual",
            "module": a["module"], "module_label": a["module_label"],
            "tab": a["tab"], "section": a["section"],
            "permission": a["permission"], "agent": a["agent"],
            "category": a["category"], "reversibility": a["reversibility"],
            "blast_radius": a["blast_radius"], "sla_minutes": a["sla_minutes"],
            "approval_trigger": a["approval_trigger"], "why_human": a["why_human"],
            "consults": a["consults"], "action_key": a["key"],
        }
    return out


ACTION_THRESHOLDS = _thresholds()


def catalog_summary() -> dict:
    """Counts the Governance tab leads with, so the header states the policy
    posture in one line without the UI re-deriving it."""
    by_class: dict[str, int] = {}
    by_module: dict[str, dict] = {}
    for a in ACTION_CATALOG:
        by_class[a["autonomy"]] = by_class.get(a["autonomy"], 0) + 1
        m = by_module.setdefault(a["module"], {
            "module": a["module"], "module_label": a["module_label"],
            "total": 0, "observe": 0, "auto": 0, "human": 0, "dual": 0})
        m["total"] += 1
        m[a["autonomy"]] += 1
    state_changing = [a for a in ACTION_CATALOG if a["category"] in ("execute", "govern")]
    autonomous = [a for a in state_changing if a["autonomy"] == "auto"]
    return {
        "total_actions": len(ACTION_CATALOG),
        "state_changing": len(state_changing),
        "autonomous": len(autonomous),
        "human_gated": len([a for a in state_changing if a["autonomy"] in ("human", "dual")]),
        "dual_control": by_class.get("dual", 0),
        "autonomy_pct": round(len(autonomous) / len(state_changing) * 100) if state_changing else 0,
        "by_class": by_class,
        "by_module": sorted(by_module.values(), key=lambda m: -m["total"]),
    }
